<script lang="ts">
	// Slice 3 T5 + B5 — terrain brush authoring layer.
	//
	// Mounts on the same viewport as the other Pixi layers. When active,
	// captures pointer-down/move/up to paint cells with the selected
	// biome. One gesture (mouse-down → drag → mouse-up) becomes one
	// undo-able command:
	//   - All paint_cells events generated by the gesture share a
	//     command_id (UUIDv4 generated locally per stroke).
	//   - The LAST POST sets payload.command_complete = true so the
	//     server's auto-anchor logic only fires at stroke boundary.
	//   - Strokes touching > 256 cells get chunked into multiple events
	//     (A3 cap; client splits, server validates).
	//
	// Brush footprint:
	//   - size=1 → just the cell under the cursor
	//   - size=3 → 3×3 square / 1-ring hex (7 cells)
	//   - size=5 → 5×5 square / 2-ring hex (19 cells)
	//
	// Eraser is just biome='unset'. Outside-voice A6: stored 'unset'
	// and missing cells render identically (transparent); the eraser
	// strokes are part of the event log so undo restores prior biome.
	//
	// Optimistic UI: the events store appends each POST's returned row
	// to the live event stream, which feeds the projection fold, which
	// repaints PixiTerrainLayer on the next $derived tick. So the user
	// sees their paint immediately, before the entire stroke is sent.

	import { getContext, onDestroy, onMount } from 'svelte';
	import { get } from 'svelte/store';
	import { PIXI_STAGE_CONTEXT, type PixiStageContext } from './pixi-context.js';
	import { mapEventsStore } from './map-events-store.js';
	import { playhead } from '$lib/features/timeline/playhead-store.js';
	import { cellAtPoint } from './grid-snap.js';
	import { biomeStyle } from './biome-textures.js';
	import { hexSizeForCanvas, hexAxialToPixel, hexVertices } from './hex-grid.js';
	import { PAINT_CELLS_MAX_PER_EVENT } from './projection.js';
	import type { BiomeKind } from './projection.js';
	import type { WorldMap } from './types.js';

	type PixiModule = typeof import('pixi.js');
	type PixiContainer = import('pixi.js').Container;
	type PixiGraphics = import('pixi.js').Graphics;
	type FederatedPointerEvent = import('pixi.js').FederatedPointerEvent;

	let {
		active = $bindable(false),
		activeMap = null,
		biome = 'plains',
		size = 1,
		onStrokeComplete = undefined
	}: {
		active?: boolean;
		activeMap?: WorldMap | null;
		biome?: BiomeKind;
		size?: 1 | 3 | 5;
		onStrokeComplete?: (cellCount: number) => void;
	} = $props();

	const stageCtx = getContext<PixiStageContext>(PIXI_STAGE_CONTEXT);
	// Server-side cap is the source of truth (projection.ts).
	const MAX_CELLS_PER_EVENT = PAINT_CELLS_MAX_PER_EVENT;

	let PIXI = $state<PixiModule | null>(null);
	let layer: PixiContainer | null = null;
	// Per-gesture state. Reset on mouse-down.
	let painting = false;
	let strokeId: string | null = null;
	let touched: Map<string, { x: number; y: number; biome: BiomeKind }> = new Map();
	let hoverCells = $state<Array<{ x: number; y: number }>>([]);

	let stagePointerDown: ((e: FederatedPointerEvent) => void) | null = null;
	let stagePointerMove: ((e: FederatedPointerEvent) => void) | null = null;
	let stagePointerUp: ((e: FederatedPointerEvent) => void) | null = null;
	let stagePointerLeave: (() => void) | null = null;

	onMount(() => {
		let cancelled = false;
		(async () => {
			const mod = await import('pixi.js');
			if (cancelled) return;
			PIXI = mod;
		})();
		return () => {
			cancelled = true;
		};
	});

	/**
	 * Brush footprint in cell-index space, centered on (cx, cy). Square
	 * uses Chebyshev-like NxN, hex uses axial distance.
	 */
	function cellsUnderBrush(
		cx: number,
		cy: number
	): Array<{ x: number; y: number }> {
		if (!activeMap) return [];
		const radius = Math.floor((size - 1) / 2);
		const cells: Array<{ x: number; y: number }> = [];
		if (activeMap.gridType === 'hex') {
			// Axial distance ≤ radius. For pointy-top axial, the "cube"
			// distance formula gives a perfectly round hex region.
			for (let dq = -radius; dq <= radius; dq++) {
				for (let dr = -radius; dr <= radius; dr++) {
					const dist =
						(Math.abs(dq) + Math.abs(dr) + Math.abs(dq + dr)) / 2;
					if (dist > radius) continue;
					const x = cx + dq;
					const y = cy + dr;
					if (x < 0 || x >= activeMap.gridCellsX) continue;
					if (y < 0 || y >= activeMap.gridCellsY) continue;
					cells.push({ x, y });
				}
			}
		} else {
			for (let dy = -radius; dy <= radius; dy++) {
				for (let dx = -radius; dx <= radius; dx++) {
					const x = cx + dx;
					const y = cy + dy;
					if (x < 0 || x >= activeMap.gridCellsX) continue;
					if (y < 0 || y >= activeMap.gridCellsY) continue;
					cells.push({ x, y });
				}
			}
		}
		return cells;
	}

	function recordTouched(cells: Array<{ x: number; y: number }>): void {
		for (const c of cells) {
			touched.set(`${c.x},${c.y}`, { x: c.x, y: c.y, biome });
		}
	}

	function pointerToCell(localX: number, localY: number): { x: number; y: number } | null {
		if (!activeMap || !activeMap.width || !activeMap.height) return null;
		return cellAtPoint(
			{ x: localX, y: localY },
			{
				gridType: activeMap.gridType,
				gridCellsX: activeMap.gridCellsX,
				gridCellsY: activeMap.gridCellsY,
				canvasWidth: activeMap.width,
				canvasHeight: activeMap.height
			}
		);
	}

	function commitStroke(): void {
		if (!activeMap || !strokeId || touched.size === 0) {
			painting = false;
			strokeId = null;
			touched = new Map();
			hoverCells = [];
			return;
		}
		const mapId = activeMap.id;
		const tPosition = get(playhead) ?? 0;
		const localStrokeId = strokeId;
		const all = Array.from(touched.values());
		const totalCells = all.length;

		// Reset the gesture SYNCHRONOUSLY, before any await. The POST is async
		// (and now optimistic), so if we left `painting` true until it resolved,
		// button-up pointermoves between two quick clicks kept recording cells
		// and the second click's pointerup committed the whole path as a line.
		// Snapshot the cells above, reset here, then fire the POST with the
		// captured data. (There's no retry path anymore — a failed commit
		// aborts — so keeping state open until success bought nothing.)
		painting = false;
		strokeId = null;
		touched = new Map();
		hoverCells = [];

		// Chunk at MAX_CELLS_PER_EVENT. Each chunk shares the strokeId;
		// only the final chunk sets command_complete=true.
		const chunks: Array<typeof all> = [];
		for (let i = 0; i < all.length; i += MAX_CELLS_PER_EVENT) {
			chunks.push(all.slice(i, i + MAX_CELLS_PER_EVENT));
		}

		void (async () => {
			try {
				for (let i = 0; i < chunks.length; i++) {
					const isLast = i === chunks.length - 1;
					await mapEventsStore.create(mapId, {
						tPosition,
						kind: 'paint_cells',
						payloadJsonb: {
							cells: chunks[i],
							command_complete: isLast
						},
						commandId: localStrokeId
					});
				}
				onStrokeComplete?.(totalCells);
			} catch (err) {
				// A permanent commit failure (400 after the grid changed,
				// sustained network loss) just drops the stroke — the gesture is
				// already reset. Chunks that already landed stay in the event log
				// under localStrokeId and undo pops them as a group.
				console.error('paint_cells stroke failed mid-flight; aborting gesture', err);
			}
		})();
	}

	$effect(() => {
		const viewport = stageCtx.viewport;
		if (!PIXI || !viewport) return;
		if (!active) return;

		stagePointerDown = (e: FederatedPointerEvent) => {
			if (e.button !== 0) return;
			// Outside-voice adversarial #3 — re-entrant pointerdown
			// guard. A second pointer (multi-touch, trackpad gesture)
			// firing pointerdown mid-stroke would otherwise reset
			// strokeId + touched and silently drop the in-flight cells.
			// First-pointer-wins: ignore subsequent down events until
			// the current stroke commits.
			if (painting) return;
			const local = e.getLocalPosition(viewport);
			const cell = pointerToCell(local.x, local.y);
			if (!cell) return;
			painting = true;
			strokeId = crypto.randomUUID();
			touched = new Map();
			recordTouched(cellsUnderBrush(cell.x, cell.y));
			hoverCells = Array.from(touched.values()).map((c) => ({ x: c.x, y: c.y }));
		};
		stagePointerMove = (e: FederatedPointerEvent) => {
			const local = e.getLocalPosition(viewport);
			const cell = pointerToCell(local.x, local.y);
			if (!cell) {
				// Cursor off the grid (out of bounds OR off-canvas).
				// We DON'T commit here — the user might drag back in
				// with the button still held, and Pixi doesn't fire
				// pointerdown a second time for a held-button gesture.
				// Just clear hover preview; pointerup is the canonical
				// commit signal.
				hoverCells = [];
				return;
			}
			const under = cellsUnderBrush(cell.x, cell.y);
			if (painting) {
				recordTouched(under);
			}
			hoverCells = under;
		};
		stagePointerUp = (_e: FederatedPointerEvent) => {
			if (!painting) return;
			void commitStroke();
		};
		stagePointerLeave = () => {
			// Outside-voice adversarial #2 — DO NOT commit on leave.
			// Cursor leaving the viewport (drag past edge then back) is
			// not a release. Committing here lost the second half of any
			// stroke that crossed the canvas edge without releasing.
			// Just clear the hover preview; the gesture stays open until
			// pointerup OR pointerupoutside fires.
			hoverCells = [];
		};

		viewport.eventMode = 'static';
		// codex P2 (PR #58): while brush mode is active, suspend the
		// pixi-viewport 'drag' plugin (installed by PixiStage via
		// viewport.drag()). Otherwise a click-and-drag paint gesture also
		// pans the viewport, so getLocalPosition(viewport) drifts under the
		// cursor mid-stroke and records unintended cells. Pinch/wheel zoom
		// stay live — only the pan-on-drag conflicts with painting. Resumed
		// on cleanup (brush deactivated / unmount). Optional-chained so a
		// mocked viewport without a plugin manager is a no-op in tests.
		const dragPlugin = viewport as unknown as {
			plugins?: { pause(name: string): void; resume(name: string): void };
		};
		dragPlugin.plugins?.pause('drag');
		viewport.on('pointerdown', stagePointerDown);
		viewport.on('pointermove', stagePointerMove);
		viewport.on('pointerup', stagePointerUp);
		viewport.on('pointerupoutside', stagePointerUp);
		viewport.on('pointerleave', stagePointerLeave);

		return () => {
			dragPlugin.plugins?.resume('drag');
			// codex P2 (PR #58): the brush can deactivate mid-stroke — a map
			// switch flips dataLoading and makes `active` false, or drawing mode
			// takes over — before pointerup fires. Clear the in-flight gesture
			// here too. Otherwise `painting` stays true: the re-entrancy guard
			// swallows the next pointerdown, and a later pointerup commits the
			// stale cells against the NEW activeMap/playhead. Mirrors the
			// failure-path reset in commitStroke.
			painting = false;
			strokeId = null;
			touched = new Map();
			hoverCells = [];
			try {
				if (stagePointerDown) viewport.off('pointerdown', stagePointerDown);
				if (stagePointerMove) viewport.off('pointermove', stagePointerMove);
				if (stagePointerUp) {
					viewport.off('pointerup', stagePointerUp);
					viewport.off('pointerupoutside', stagePointerUp);
				}
				if (stagePointerLeave) viewport.off('pointerleave', stagePointerLeave);
			} catch (_) {
				/* viewport may be torn down */
			}
			stagePointerDown = null;
			stagePointerMove = null;
			stagePointerUp = null;
			stagePointerLeave = null;
		};
	});

	// Hover preview render. Lights up the cells currently under the
	// brush at low alpha so the user knows what'll get painted on click.
	//
	// /review perf — uses ONE persistent Graphics with .clear() per
	// tick instead of destroying + reallocating on every pointermove.
	// At 60-120 pointermove events/sec during drag, the old destroy-
	// per-frame pattern thrashed GC. Pixi v8 Graphics.clear() reuses
	// the geometry buffer.
	let previewGraphics: PixiGraphics | null = null;
	$effect(() => {
		const viewport = stageCtx.viewport;
		if (!PIXI || !viewport) return;

		// Reference reactive deps.
		const cells = hoverCells;
		const map = activeMap;
		const isActive = active;
		const b = biome;

		if (!layer) {
			layer = new PIXI.Container();
			viewport.addChild(layer);
		}
		if (!previewGraphics) {
			previewGraphics = new PIXI.Graphics();
			layer.addChild(previewGraphics);
		}

		previewGraphics.clear();

		if (!isActive || !map || !map.width || !map.height || cells.length === 0) {
			return;
		}

		const style = biomeStyle(b);
		// Hover preview at fixed alpha 0.5 (regardless of biome's base
		// alpha) so the user gets consistent visual weight per stroke
		// regardless of biome.
		const previewAlpha = b === 'unset' ? 0.2 : 0.5;
		if (map.gridType === 'hex') {
			drawHexPreview(previewGraphics, cells, map);
		} else {
			drawSquarePreview(previewGraphics, cells, map);
		}
		previewGraphics.fill({
			color: b === 'unset' ? 0xef4444 : style.color,
			alpha: previewAlpha
		});
	});

	function drawSquarePreview(
		g: PixiGraphics,
		cells: Array<{ x: number; y: number }>,
		map: WorldMap
	): void {
		if (!map.width || !map.height) return;
		const cellW = map.width / map.gridCellsX;
		const cellH = map.height / map.gridCellsY;
		for (const c of cells) {
			g.rect(c.x * cellW, c.y * cellH, cellW, cellH);
		}
	}

	function drawHexPreview(
		g: PixiGraphics,
		cells: Array<{ x: number; y: number }>,
		map: WorldMap
	): void {
		if (!map.width || !map.height) return;
		const sizeHex = hexSizeForCanvas(map.gridCellsX, map.gridCellsY, map.width, map.height);
		for (const c of cells) {
			const center = hexAxialToPixel(c.x, c.y, sizeHex);
			const verts = hexVertices(center.x, center.y, sizeHex);
			g.moveTo(verts[0].x, verts[0].y);
			for (let i = 1; i < verts.length; i++) {
				g.lineTo(verts[i].x, verts[i].y);
			}
			g.closePath();
		}
	}

	onDestroy(() => {
		const viewport = stageCtx.viewport;
		try {
			if (viewport && stagePointerDown) viewport.off('pointerdown', stagePointerDown);
			if (viewport && stagePointerMove) viewport.off('pointermove', stagePointerMove);
			if (viewport && stagePointerUp) {
				viewport.off('pointerup', stagePointerUp);
				viewport.off('pointerupoutside', stagePointerUp);
			}
			if (viewport && stagePointerLeave) viewport.off('pointerleave', stagePointerLeave);
		} catch (_) {
			/* viewport may be torn down */
		}
		if (layer) {
			try {
				layer.destroy({ children: true });
			} catch (_) {
				/* parent app may have been destroyed first */
			}
			layer = null;
		}
	});
</script>
