<script lang="ts">
	// Slice 3 T5 + B5 — terrain brush authoring layer.
	//
	// Mounts on the same viewport as the other Pixi layers. When active,
	// captures pointer-down/move/up to paint cells with the selected
	// biome. One gesture (mouse-down → drag → mouse-up) becomes one
	// undo-able command:
	//   - All paint_cells events generated by the gesture share a
	//     command_id (UUIDv4 generated locally per stroke).
	//   - The LAST POST sets payload.command_complete = true so the
	//     server's auto-anchor logic only fires at stroke boundary.
	//   - Strokes touching > 256 cells get chunked into multiple events
	//     (A3 cap; client splits, server validates).
	//
	// Brush footprint:
	//   - size=1 → just the cell under the cursor
	//   - size=3 → 3×3 square / 1-ring hex (7 cells)
	//   - size=5 → 5×5 square / 2-ring hex (19 cells)
	//
	// Eraser is just biome='unset'. Outside-voice A6: stored 'unset'
	// and missing cells render identically (transparent); the eraser
	// strokes are part of the event log so undo restores prior biome.
	//
	// Optimistic UI: the events store appends each POST's returned row
	// to the live event stream, which feeds the projection fold, which
	// repaints PixiTerrainLayer on the next $derived tick. So the user
	// sees their paint immediately, before the entire stroke is sent.

	import { getContext, onDestroy, onMount } from 'svelte';
	import { get } from 'svelte/store';
	import { PIXI_STAGE_CONTEXT, type PixiStageContext } from './pixi-context.js';
	import { mapEventsStore } from './map-events-store.js';
	import { playhead } from '$lib/features/timeline/playhead-store.js';
	import { cellAtPoint } from './grid-snap.js';
	import { biomeStyle } from './biome-textures.js';
	import { hexSizeForCanvas, hexAxialToPixel, hexVertices } from './hex-grid.js';
	import type { BiomeKind } from './projection.js';
	import type { WorldMap } from './types.js';

	type PixiModule = typeof import('pixi.js');
	type PixiContainer = import('pixi.js').Container;
	type PixiGraphics = import('pixi.js').Graphics;
	type FederatedPointerEvent = import('pixi.js').FederatedPointerEvent;

	let {
		active = $bindable(false),
		activeMap = null,
		biome = 'plains',
		size = 1,
		onStrokeComplete = undefined
	}: {
		active?: boolean;
		activeMap?: WorldMap | null;
		biome?: BiomeKind;
		size?: 1 | 3 | 5;
		onStrokeComplete?: (cellCount: number) => void;
	} = $props();

	const stageCtx = getContext<PixiStageContext>(PIXI_STAGE_CONTEXT);
	const MAX_CELLS_PER_EVENT = 256;

	let PIXI = $state<PixiModule | null>(null);
	let layer: PixiContainer | null = null;
	// Per-gesture state. Reset on mouse-down.
	let painting = false;
	let strokeId: string | null = null;
	let touched: Map<string, { x: number; y: number; biome: BiomeKind }> = new Map();
	let hoverCells = $state<Array<{ x: number; y: number }>>([]);

	let stagePointerDown: ((e: FederatedPointerEvent) => void) | null = null;
	let stagePointerMove: ((e: FederatedPointerEvent) => void) | null = null;
	let stagePointerUp: ((e: FederatedPointerEvent) => void) | null = null;
	let stagePointerLeave: (() => void) | null = null;

	onMount(() => {
		let cancelled = false;
		(async () => {
			const mod = await import('pixi.js');
			if (cancelled) return;
			PIXI = mod;
		})();
		return () => {
			cancelled = true;
		};
	});

	/**
	 * Brush footprint in cell-index space, centered on (cx, cy). Square
	 * uses Chebyshev-like NxN, hex uses axial distance.
	 */
	function cellsUnderBrush(
		cx: number,
		cy: number
	): Array<{ x: number; y: number }> {
		if (!activeMap) return [];
		const radius = Math.floor((size - 1) / 2);
		const cells: Array<{ x: number; y: number }> = [];
		if (activeMap.gridType === 'hex') {
			// Axial distance ≤ radius. For pointy-top axial, the "cube"
			// distance formula gives a perfectly round hex region.
			for (let dq = -radius; dq <= radius; dq++) {
				for (let dr = -radius; dr <= radius; dr++) {
					const dist =
						(Math.abs(dq) + Math.abs(dr) + Math.abs(dq + dr)) / 2;
					if (dist > radius) continue;
					const x = cx + dq;
					const y = cy + dr;
					if (x < 0 || x >= activeMap.gridCellsX) continue;
					if (y < 0 || y >= activeMap.gridCellsY) continue;
					cells.push({ x, y });
				}
			}
		} else {
			for (let dy = -radius; dy <= radius; dy++) {
				for (let dx = -radius; dx <= radius; dx++) {
					const x = cx + dx;
					const y = cy + dy;
					if (x < 0 || x >= activeMap.gridCellsX) continue;
					if (y < 0 || y >= activeMap.gridCellsY) continue;
					cells.push({ x, y });
				}
			}
		}
		return cells;
	}

	function recordTouched(cells: Array<{ x: number; y: number }>): void {
		for (const c of cells) {
			touched.set(`${c.x},${c.y}`, { x: c.x, y: c.y, biome });
		}
	}

	function pointerToCell(localX: number, localY: number): { x: number; y: number } | null {
		if (!activeMap || !activeMap.width || !activeMap.height) return null;
		return cellAtPoint(
			{ x: localX, y: localY },
			{
				gridType: activeMap.gridType,
				gridCellsX: activeMap.gridCellsX,
				gridCellsY: activeMap.gridCellsY,
				canvasWidth: activeMap.width,
				canvasHeight: activeMap.height
			}
		);
	}

	async function commitStroke(): Promise<void> {
		if (!activeMap || !strokeId || touched.size === 0) {
			painting = false;
			strokeId = null;
			touched = new Map();
			hoverCells = [];
			return;
		}
		const mapId = activeMap.id;
		const tPosition = get(playhead) ?? 0;
		const all = Array.from(touched.values());
		// Chunk at MAX_CELLS_PER_EVENT. Each chunk shares the strokeId;
		// only the final chunk sets command_complete=true.
		const chunks: Array<typeof all> = [];
		for (let i = 0; i < all.length; i += MAX_CELLS_PER_EVENT) {
			chunks.push(all.slice(i, i + MAX_CELLS_PER_EVENT));
		}
		const totalCells = all.length;
		// Reset gesture state BEFORE the awaits so a rapid second stroke
		// has a fresh slate.
		const localStrokeId = strokeId;
		touched = new Map();
		strokeId = null;
		painting = false;
		hoverCells = [];

		try {
			for (let i = 0; i < chunks.length; i++) {
				const isLast = i === chunks.length - 1;
				await mapEventsStore.create(mapId, {
					tPosition,
					kind: 'paint_cells',
					payloadJsonb: {
						cells: chunks[i],
						command_complete: isLast
					},
					commandId: localStrokeId
				});
			}
			onStrokeComplete?.(totalCells);
		} catch (err) {
			// Partial-stroke failure: leave already-committed chunks in
			// place (server saw them, they're in the event log) and
			// surface the error to the console. Future polish: UI toast.
			console.error('paint_cells stroke failed mid-flight', err);
		}
	}

	$effect(() => {
		const viewport = stageCtx.viewport;
		if (!PIXI || !viewport) return;
		if (!active) return;

		stagePointerDown = (e: FederatedPointerEvent) => {
			if (e.button !== 0) return;
			const local = e.getLocalPosition(viewport);
			const cell = pointerToCell(local.x, local.y);
			if (!cell) return;
			painting = true;
			strokeId = crypto.randomUUID();
			touched = new Map();
			recordTouched(cellsUnderBrush(cell.x, cell.y));
			hoverCells = Array.from(touched.values()).map((c) => ({ x: c.x, y: c.y }));
		};
		stagePointerMove = (e: FederatedPointerEvent) => {
			const local = e.getLocalPosition(viewport);
			const cell = pointerToCell(local.x, local.y);
			if (!cell) {
				hoverCells = [];
				return;
			}
			const under = cellsUnderBrush(cell.x, cell.y);
			if (painting) {
				recordTouched(under);
			}
			hoverCells = under;
		};
		stagePointerUp = (_e: FederatedPointerEvent) => {
			if (!painting) return;
			void commitStroke();
		};
		stagePointerLeave = () => {
			// Leaving the viewport mid-stroke commits whatever was
			// touched. Otherwise the user has a hung in-progress stroke
			// that never POSTs.
			if (painting) {
				void commitStroke();
			} else {
				hoverCells = [];
			}
		};

		viewport.eventMode = 'static';
		viewport.on('pointerdown', stagePointerDown);
		viewport.on('pointermove', stagePointerMove);
		viewport.on('pointerup', stagePointerUp);
		viewport.on('pointerupoutside', stagePointerUp);
		viewport.on('pointerleave', stagePointerLeave);

		return () => {
			try {
				if (stagePointerDown) viewport.off('pointerdown', stagePointerDown);
				if (stagePointerMove) viewport.off('pointermove', stagePointerMove);
				if (stagePointerUp) {
					viewport.off('pointerup', stagePointerUp);
					viewport.off('pointerupoutside', stagePointerUp);
				}
				if (stagePointerLeave) viewport.off('pointerleave', stagePointerLeave);
			} catch (_) {
				/* viewport may be torn down */
			}
			stagePointerDown = null;
			stagePointerMove = null;
			stagePointerUp = null;
			stagePointerLeave = null;
		};
	});

	// Hover preview render. Lights up the cells currently under the
	// brush at low alpha so the user knows what'll get painted on click.
	$effect(() => {
		const viewport = stageCtx.viewport;
		if (!PIXI || !viewport) return;

		// Reference reactive deps.
		const cells = hoverCells;
		const map = activeMap;
		const isActive = active;
		const b = biome;

		if (!layer) {
			layer = new PIXI.Container();
			viewport.addChild(layer);
		}
		for (const child of layer.removeChildren()) {
			child.destroy();
		}

		if (!isActive || !map || !map.width || !map.height || cells.length === 0) {
			return;
		}

		const style = biomeStyle(b);
		// Hover preview at fixed alpha 0.5 (regardless of biome's base
		// alpha) so the user gets consistent visual weight per stroke
		// regardless of biome.
		const previewAlpha = b === 'unset' ? 0.2 : 0.5;
		const g: PixiGraphics = new PIXI.Graphics();
		if (map.gridType === 'hex') {
			drawHexPreview(g, cells, map);
		} else {
			drawSquarePreview(g, cells, map);
		}
		g.fill({
			color: b === 'unset' ? 0xef4444 : style.color,
			alpha: previewAlpha
		});
		layer.addChild(g);
	});

	function drawSquarePreview(
		g: PixiGraphics,
		cells: Array<{ x: number; y: number }>,
		map: WorldMap
	): void {
		if (!map.width || !map.height) return;
		const cellW = map.width / map.gridCellsX;
		const cellH = map.height / map.gridCellsY;
		for (const c of cells) {
			g.rect(c.x * cellW, c.y * cellH, cellW, cellH);
		}
	}

	function drawHexPreview(
		g: PixiGraphics,
		cells: Array<{ x: number; y: number }>,
		map: WorldMap
	): void {
		if (!map.width || !map.height) return;
		const sizeHex = hexSizeForCanvas(map.gridCellsX, map.gridCellsY, map.width, map.height);
		for (const c of cells) {
			const center = hexAxialToPixel(c.x, c.y, sizeHex);
			const verts = hexVertices(center.x, center.y, sizeHex);
			g.moveTo(verts[0].x, verts[0].y);
			for (let i = 1; i < verts.length; i++) {
				g.lineTo(verts[i].x, verts[i].y);
			}
			g.closePath();
		}
	}

	onDestroy(() => {
		const viewport = stageCtx.viewport;
		try {
			if (viewport && stagePointerDown) viewport.off('pointerdown', stagePointerDown);
			if (viewport && stagePointerMove) viewport.off('pointermove', stagePointerMove);
			if (viewport && stagePointerUp) {
				viewport.off('pointerup', stagePointerUp);
				viewport.off('pointerupoutside', stagePointerUp);
			}
			if (viewport && stagePointerLeave) viewport.off('pointerleave', stagePointerLeave);
		} catch (_) {
			/* viewport may be torn down */
		}
		if (layer) {
			try {
				layer.destroy({ children: true });
			} catch (_) {
				/* parent app may have been destroyed first */
			}
			layer = null;
		}
	});
</script>
